# Generated by Django 5.1.7 on 2025-03-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationnn_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pictures/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='quantity_needed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
