# Generated by Django 5.1.7 on 2025-03-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationnn_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='license_id',
            new_name='org_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='quantity_donated',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('household_essentials', 'Household Essentials'), ('clothing', 'Clothing'), ('footwear', 'Footwear'), ('grains', 'Grains'), ('pulses', 'Pulses'), ('mobility_aids', 'Mobility Aids'), ('educational_supplies', 'Educational Supplies')], default='grains', max_length=50),
        ),
        migrations.AddField(
            model_name='item',
            name='item_name',
            field=models.CharField(default='Dress', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pictures/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='org_name',
            field=models.CharField(default='ABC', max_length=255, verbose_name='Organization Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='organization_pictures/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_needed',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
