# Generated by Django 5.1.7 on 2025-03-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationnn_app', '0002_organization_item_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_picture',
            field=models.ImageField(blank=True, null=True, upload_to='item_pictures/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_needed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
