# Generated by Django 5.1.7 on 2025-03-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationnn_app', '0003_item_item_picture_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='organization_pictures/'),
        ),
    ]
