# Generated by Django 5.1.7 on 2025-03-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationnn_app', '0004_organization_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
