# Generated by Django 5.1.7 on 2025-03-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationnn_app', '0006_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity_donated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_needed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
