# Generated by Django 5.1.7 on 2025-03-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationnn_app', '0007_alter_item_quantity_donated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity_donated',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('grains', 'Grains'), ('pulses', 'Pulses'), ('clothes', 'Clothes'), ('footwears', 'Footwears'), ('wheelchair', 'Wheelchair'), ('walking_stick', 'Walking Stick'), ('rice', 'Rice'), ('bed', 'Bed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
