# Generated by Django 5.1.7 on 2025-03-14 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationnn_app', '0008_remove_item_quantity_donated_alter_item_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='license_id',
            new_name='org_id',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='name',
            new_name='org_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='item_picture',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='quantity_needed',
        ),
        migrations.AddField(
            model_name='item',
            name='item_category',
            field=models.CharField(choices=[('household_essentials', 'Household Essentials'), ('clothing', 'Clothing'), ('footwear', 'Footwear'), ('grains', 'Grains'), ('pulses', 'Pulses'), ('mobility_aids', 'Mobility Aids'), ('educational_supplies', 'Educational Supplies')], default='grains', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity_needed',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
