# Generated by Django 5.1.7 on 2025-03-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donationnn_app', '0009_rename_name_item_item_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='org_name',
            field=models.CharField(max_length=255, verbose_name='Organization Name'),
        ),
    ]
